"""initial clean schema

Revision ID: 6d4c16cc07f5
Revises: 
Create Date: 2025-12-23 17:12:40.396169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4c16cc07f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.Column('jaw_tension', sa.Integer(), nullable=True),
    sa.Column('shoulder_tension', sa.Integer(), nullable=True),
    sa.Column('stomach_discomfort', sa.Integer(), nullable=True),
    sa.Column('headache', sa.Integer(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('negative_thought', sa.Text(), nullable=True),
    sa.Column('reframed_thought', sa.Text(), nullable=True),
    sa.Column('gratitude_1', sa.String(length=255), nullable=True),
    sa.Column('gratitude_2', sa.String(length=255), nullable=True),
    sa.Column('gratitude_3', sa.String(length=255), nullable=True),
    sa.Column('affirmation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_reflection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boundary_check', sa.Text(), nullable=True),
    sa.Column('weekly_goal', sa.Text(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_reflection')
    op.drop_table('entry')
    op.drop_table('user')
    # ### end Alembic commands ###
